export {default as Hero} from './Hero/Hero'
export {default as Features} from './FeaturesNile/Features'
export {default as Faq} from './FAQ/Faq'
export {default as Footer} from './Footer/Footer'
export {default as Aboutus} from './AboutNile/Aboutus'
export {default as UseCase} from './useCase/UseCase'
export {default as Nav} from './Navbar/Nav'
export { default as LogoCompanies } from './LogoCompanies/LogoCompanies'
export {default as ContactWay} from './Contactways/ContactWay'
export { default as Testimonies } from './Testimonial/Testimonies'
export {default as OurValues} from './Values/OurValues'
export { default as OurTeam } from './Team/OurTeam'
export {default as ScrollToTop} from './ScrollToTop'